[tool.pyright]
  exclude = ["tests", "arc/dsl", "scripts", "data", "notebooks"]
  venvPath = "."
  venv = ".venv"

[tool.ruff]
exclude = ["arc/dsl", "data", "notebooks"]

[tool.pytest.ini_options]
pythonpath = ["."]

